/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladores06042021;

import Utils.ExpressionTree;
import static Utils.GenerarExpresion.empiesaConOperador;
import static Utils.GenerarExpresion.evaluarAlternaciones;
import static Utils.GenerarExpresion.infixToPostfixV2;
import static Utils.GenerarExpresion.infixToPrefix;
import static Utils.GenerarExpresion.terminaConOperador;
import static Utils.GenerarExpresion.validarParentesis;
import static Utils.GenerarExpresion.valuarExpresion;
import Utils.GraficadorArboles;
import Utils.Node;
import Utils.Node_v2;
import Utils.PostfixPojo;
import javax.swing.JFrame;

/**
 * @author Tote
 * @author Brodner
 * @author David
 * @author Armando Santos
 */
public class MainForm extends javax.swing.JFrame {

    private Node root;
    private Node_v2 root2;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        //NewPanelTest panel = new NewPanelTest();
        //Graficador mGraficador = new Graficador();
        //spArbolSinactico.add(mGraficador);
        //this.getContentPane().add(panel);

        initComponents();
        this.setLocationRelativeTo(null);
        LimpiarTodasLasLabes();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngresoExpresion = new javax.swing.JTextArea();
        btnGenerar = new javax.swing.JButton();
        spArbolSinactico = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArbol = new javax.swing.JTextArea();
        btnVisualizarGraficamente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        lblInfijo = new javax.swing.JLabel();
        lblPosfijo = new javax.swing.JLabel();
        lblPrefix = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lblError = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAVINCIANOS");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresa la expresion"));

        txtIngresoExpresion.setColumns(20);
        txtIngresoExpresion.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txtIngresoExpresion.setRows(5);
        jScrollPane1.setViewportView(txtIngresoExpresion);

        btnGenerar.setText("Generar Expresiones");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerar)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        spArbolSinactico.setBorder(javax.swing.BorderFactory.createTitledBorder("Arbol"));

        txtArbol.setColumns(20);
        txtArbol.setRows(5);
        txtArbol.setEnabled(false);
        jScrollPane2.setViewportView(txtArbol);

        btnVisualizarGraficamente.setText("Visualizar en forma grafica");
        btnVisualizarGraficamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarGraficamenteActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Creditos"));

        jLabel1.setText("Desarrollado Por:");

        jLabel2.setText("David Alfredo Díaz Veras -  201901175");

        jLabel3.setText("Armando Emmanuel Santos Coy - 201900674");

        jLabel4.setText("Kevyn Salvador Posadas Tote -  201901858");

        jLabel5.setText("Brodner Morales - 201902589");

        jLabel6.setText("UNIVERSIDAD DA VINCI DE GUATEMALA - 2021");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout spArbolSinacticoLayout = new javax.swing.GroupLayout(spArbolSinactico);
        spArbolSinactico.setLayout(spArbolSinacticoLayout);
        spArbolSinacticoLayout.setHorizontalGroup(
            spArbolSinacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spArbolSinacticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spArbolSinacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarGraficamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        spArbolSinacticoLayout.setVerticalGroup(
            spArbolSinacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spArbolSinacticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spArbolSinacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spArbolSinacticoLayout.createSequentialGroup()
                        .addComponent(btnVisualizarGraficamente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        lblInfijo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblInfijo.setText("jLabel1");

        lblPosfijo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPosfijo.setText("jLabel2");

        lblPrefix.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPrefix.setText("jLabel7");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfijo)
                    .addComponent(lblPosfijo)
                    .addComponent(lblPrefix))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfijo)
                .addGap(45, 45, 45)
                .addComponent(lblPrefix)
                .addGap(43, 43, 43)
                .addComponent(lblPosfijo)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Consola"));

        lblError.setColumns(20);
        lblError.setRows(5);
        jScrollPane4.setViewportView(lblError);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculadora"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spArbolSinactico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spArbolSinactico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String infija = txtIngresoExpresion.getText();
        LimpiarTodasLasLabes();
        if (!infija.isEmpty()) {
            //Funciona con String
            lblInfijo.setText("Expresion Infija: " + infija.replace(" ", ""));

            //Validamos que los parentesis esten correctamente anidados
            if (validarParentesis(infija, lblError)) {
                //Validamos que la emprecion no inicie con un operador
                if (empiesaConOperador(infija, lblError)) {
                    // campoInicia.setIcon(new javax.swing.ImageIcon(getClass().getResource(noAcreditado)));
                    return;
                } else {
                    //Validamos que la emprecion no termine con un operador
                    if (terminaConOperador(infija, lblError)) {
                        // campoTermina.setIcon(new javax.swing.ImageIcon(getClass().getResource(noAcreditado)));
                        return;
                    } else {
                        //Evaluamos que la exprecion este correctamente alternada
                        if (evaluarAlternaciones(infija, lblError)) {
                            //Todo esta correcto
                            PostfixPojo posfija = infixToPostfixV2(infija.replace(" ", ""));
                            String prefija = infixToPrefix(infija);
                            lblPrefix.setText("Expresion Prefija: " + prefija);
                            lblPosfijo.setText("Expresion Postfija: " + posfija.getExpresion());
                            root = ExpressionTree.constructTree(posfija.getExpresionArray(), txtArbol, posfija.getExpresion(), infija, prefija);
                            lblError.append("\n-> Resultado Expresion: " + valuarExpresion(posfija.getExpresionArray(), lblError));

                        } else {
                            // campoAlternada.setIcon(new javax.swing.ImageIcon(getClass().getResource(noAcreditado)));
                            return;
                        }
                    }
                }
            } else {
                //  campoParentesis.setIcon(new javax.swing.ImageIcon(getClass().getResource(noAcreditado)));
                return;
            }

            //Funciona con Char
            /* String posfija = infixToPostfix(infija.replace(" ", ""));
            lblPosfijo.setText("Expresion Postfija: " + posfija);
            char[] charArray = posfija.toCharArray();
            root2 = ExpressionTree.constructTree(charArray, txtArbol);*/
        } else {
            System.out.println("No hay datos para analizar!");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnVisualizarGraficamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarGraficamenteActionPerformed
        JFrame frame = new JFrame("Binary Tree");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(new GraficadorArboles(root));
        frame.pack();
        frame.setBounds(50, 50, 500, 500);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_btnVisualizarGraficamenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnVisualizarGraficamente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea lblError;
    private javax.swing.JLabel lblInfijo;
    private javax.swing.JLabel lblPosfijo;
    private javax.swing.JLabel lblPrefix;
    private javax.swing.JPanel spArbolSinactico;
    private javax.swing.JTextArea txtArbol;
    private javax.swing.JTextArea txtIngresoExpresion;
    // End of variables declaration//GEN-END:variables

    private void LimpiarTodasLasLabes() {
        lblInfijo.setText("");
        lblPrefix.setText("");
        lblPosfijo.setText("");
        lblError.setText("");
        txtArbol.setText("");
        root = null;
    }
}
